name: PatiteParserDart
version: 0.0.3
description: A simple customizable parsing tool.
environment:
  sdk: '>=2.0.0'

dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^2.4.0
  resource: ^2.1.6
  
dev_dependencies:
  webdev: ^1.0.0
  