name: PetiteParserDart
version: 1.1.0
description: A simple customizable parsing tool.
environment:
  sdk: '>=2.0.0'

dependencies:
  build_runner: ^1.10.0
  build_test: ^1.2.2
  build_web_compilers: ^2.11.0
  resource: ^2.1.6

dev_dependencies:
  webdev: ^2.6.2
  