name: PetiteParserDart
version: 1.3.0
description: A simple customizable parsing tool.
environment:
  sdk: '>=2.13.3'

dependencies:
  build_runner: ^1.6.2
  build_test: ^2.0.0
  build_web_compilers: ^2.0.0

dev_dependencies:
  webdev: ^2.7.4
  