name: PatiteParserDart
version: 0.0.1
description: A simple customizable parsing tool.
environment:
  sdk: '>=2.0.0'

dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
  
dev_dependencies:
  webdev: ^1.0.0
  